### ISSUE TITLE
清除用户数据后 软件用不了

### ISSUE THREAD

**Issue by pinkxxy** [Zeal-L/BiliBili-Manga-Downloader#110]
### 问题描述

清除用户数据后 软件用不了

### 预期行为

清除用户数据后 软件用不了

### 实际行为

14:28:38 | ERROR | MainGUI: eventFilter - 154 | 主窗口事件过滤器出错！
'PySide6.QtCore.QObject.eventFilter' called with wrong argument types:
  PySide6.QtCore.QObject.eventFilter(QWidgetItem, QEvent)
Supported signatures:
  PySide6.QtCore.QObject.eventFilter(PySide6.QtCore.QObject, PySide6.QtCore.QEvent)
23:43:11 | ERROR | MainGUI: closeEvent - 101 | 清除用户数据失败 - 目录:C:\Users\pinkx\AppData\Roaming\BiliBili-Manga-Downloader
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\pinkx\\AppData\\Roaming\\BiliBili-Manga-Downloader\\logs\\ERROR.log'
23:43:11 | INFO | MainGUI: closeEvent - 103 | 
Traceback (most recent call last):
  File "app.py", line 24, in <module>
  File "src\ui\MainGUI.py", line 73, in __init__
  File "src\ui\SettingUI.py", line 47, in __init__
  File "src\ui\SettingUI.py", line 141, in init_cookie
  File "src\ui\SettingUI.py", line 190, in is_cookie_valid
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\ui\SettingUI.py", line 177, in _
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 496, in _make_request
  File "urllib3\connection.py", line 394, in request
  File "urllib3\connection.py", line 308, in putheader
  File "http\client.py", line 1264, in putheader
ValueError: Invalid header value b'SESSDATA=e955d243%2C1720266150%2C20fa2%2A11CjBkaTjmhC7nVGgY9JPMPYag4fYku8Xamq2TSv-AUCu5YwvH6-t3aZq8RvlX88DI-CkSVkM3QXpsRFRIMjFXTVY5dF8wRjQyX0VWRDUwWmYzRWwtNW5DcjJHWWplYkJ4XzRIbHJIcmNlQW9oSGlsTExKZmI5WlBLTVd0MXhtYWhBYTJiYW42bFJBIIEC\n'

### 截图或录屏

![QQ截图20240109000303](https://github.com/Zeal-L/BiliBili-Manga-Downloader/assets/155056096/50f8218d-ef7f-48fb-8a19-aa33faf202c7)

### 哔哩哔哩漫画下载器版本号

1.5.0

### 系统环境

Windows11

### 日志

[ERROR.log](https://github.com/Zeal-L/BiliBili-Manga-Downloader/files/13863337/ERROR.log)

**Comment by Zeal-L** [comment]
@pinkxxy  你尝试一下把缓存文件夹全部删掉再重新打开软件
