### ISSUE TITLE
[Bug] 证书验证错误

### ISSUE THREAD

**Issue by AlexEisie** [Zeal-L/BiliBili-Manga-Downloader#139]
### 问题描述

似乎是由于Let's Encrypt证书的链支持更新，尝试连接时无法验证证书。如果是普遍问题，是否考虑忽略SSL验证？(TLS/1.2)

### 预期行为

BiliPlus 连接

### 实际行为

证书验证失败

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Windows10

### 日志

Traceback (most recent call last):
  File "src\ui\SettingUI.py", line 261, in check_biliplus_cookie_valid
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\ui\SettingUI.py", line 247, in _
  File "src\ui\SettingUI.py", line 244, in _
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.biliplus.com', port=443): Max retries exceeded with url: /manga/?act=read&mangaid=26551&epid=316882 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

**Comment by shadlc** [comment]
经多设备测试以及群友使用状况观测，未复现此问题，应不是普遍问题，如有需要请自行修改源码使用，或请自行检查是否使用了SSL加解密工具处理或遭受中间人攻击。
