### ISSUE TITLE
[Bug] 【代理/端口问题？】由于目标计算机积极拒绝，无法连接。 Failed to establish a new connection.

### ISSUE THREAD

**Issue by EIKO4O4** [Zeal-L/BiliBili-Manga-Downloader#144]
# 问题描述

检测cookie时会报错，没有用代理（用了也不行）

<details><summary>输入了正确的 biliPlus  cookie 后的 log</summary>
<p>

21:36:43 | WARNING | SettingUI: _ - 248 | 测试BiliPlus Cookie是否有效失败! 重试中...
HTTPSConnectionPool(host='www.biliplus.com', port=443): Max retries exceeded with url: /manga/ (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A29C8D760>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
21:36:46 | WARNING | SettingUI: _ - 248 | 测试BiliPlus Cookie是否有效失败! 重试中...
HTTPSConnectionPool(host='www.biliplus.com', port=443): Max retries exceeded with url: /manga/ (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A29C8EE40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
21:36:46 | ERROR | SettingUI: check_biliplus_cookie_valid - 277 | 重复测试biliplus Cookie是否有效多次后失败!
21:36:46 | ERROR | SettingUI: check_biliplus_cookie_valid - 278 | HTTPSConnectionPool(host='www.biliplus.com', port=443): Max retries exceeded with url: /manga/ (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A29C8EE40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
Traceback (most recent call last):
  File "urllib3\connection.py", line 198, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 779, in urlopen
  File "urllib3\connectionpool.py", line 1048, in _prepare_proxy
  File "urllib3\connection.py", line 616, in connect
  File "urllib3\connection.py", line 213, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000017A29C8EE40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A29C8EE40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.biliplus.com', port=443): Max retries exceeded with url: /manga/ (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A29C8EE40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\ui\SettingUI.py", line 262, in check_biliplus_cookie_valid
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\ui\SettingUI.py", line 249, in _
  File "src\ui\SettingUI.py", line 246, in _
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.biliplus.com', port=443): Max retries exceeded with url: /manga/ (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017A29C8EE40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

</p>
</details> 

#### 预期行为

正常

#### 实际行为

报错

### 哔哩哔哩漫画下载器版本号

v1.5.1

## 系统环境

Windows11 22H2

# 日志

[ERROR.log](https://github.com/Zeal-L/BiliBili-Manga-Downloader/files/15322452/ERROR.log)

**Comment by EIKO4O4** [comment]
应该是我自己电脑的问题，我这破环境用很多软件都有网络问题，就不麻烦作者了
