### ISSUE TITLE
[Bug] Biliplus 哈希校验失败

### ISSUE THREAD

**Issue by sprinox** [Zeal-L/BiliBili-Manga-Downloader#166]
### 问题描述

下载部分章节时出现哈希校验失败的问题
```
11:49:55 | WARNING | Episode: _ - 553 | 《在魔王城说晚安》章节：368 第368话 第三百六十八夜 噩梦的足迹 - 1 - https://www.biliplus.com/manga/?act=get_image_url&epid=1539057&request_time=1725680974&file=07f9b3b7010d8cb3cbb5724221df8e43d648f9e0.webp&append= - 下载内容Checksum不正确! 重试中...
	"33269b86f76f0fb4fede864d283ddbfc" ≠ 40696ec2a104e8c2f1e439fa231c3209
```
分析后认为可能是biliplus发送的哈希值有误。这类资源目前为止都是webp格式的，没能请求到jpg格式的文件（b站有jpg的）。

### 预期行为

.

### 实际行为

.

### 哔哩哔哩漫画下载器版本号

bae7f5f

### 系统环境

Windows11

### 日志

```
11:49:55 | WARNING | Episode: _ - 553 | 《在魔王城说晚安》章节：366 第366话 第三百六十六夜 在支持的基础上开始 - 1 - https://www.biliplus.com/manga/?act=get_image_url&epid=1521923&request_time=1725680974&file=78a036148a35931fe8ebd8f4a9fd51464d67d0f2.webp&append= - 下载内容Checksum不正确! 重试中...
	"7fbdb67eda0808ac2c83ec84a009d735" ≠ 1a3dd15b4dccd0f1720a63d6eabcf22d
11:49:55 | ERROR | Episode: downloadImg - 563 | 《在魔王城说晚安》章节：366 第366话 第三百六十六夜 在支持的基础上开始 - 1 - https://www.biliplus.com/manga/?act=get_image_url&epid=1521923&request_time=1725680974&file=78a036148a35931fe8ebd8f4a9fd51464d67d0f2.webp&append= 重复下载图片多次后失败!

11:49:55 | ERROR | Episode: downloadImg - 566 | 
Traceback (most recent call last):
  File "src\Episode.py", line 561, in downloadImg
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\Episode.py", line 557, in _
requests.exceptions.HTTPError
11:49:55 | WARNING | Episode: _ - 553 | 《在魔王城说晚安》章节：368 第368话 第三百六十八夜 噩梦的足迹 - 1 - https://www.biliplus.com/manga/?act=get_image_url&epid=1539057&request_time=1725680974&file=07f9b3b7010d8cb3cbb5724221df8e43d648f9e0.webp&append= - 下载内容Checksum不正确! 重试中...
	"33269b86f76f0fb4fede864d283ddbfc" ≠ 40696ec2a104e8c2f1e439fa231c3209
11:49:55 | ERROR | Episode: downloadImg - 563 | 《在魔王城说晚安》章节：368 第368话 第三百六十八夜 噩梦的足迹 - 1 - https://www.biliplus.com/manga/?act=get_image_url&epid=1539057&request_time=1725680974&file=07f9b3b7010d8cb3cbb5724221df8e43d648f9e0.webp&append= 重复下载图片多次后失败!

11:49:55 | ERROR | Episode: downloadImg - 566 | 
Traceback (most recent call last):
  File "src\Episode.py", line 561, in downloadImg
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\Episode.py", line 557, in _
requests.exceptions.HTTPError
11:49:56 | WARNING | Episode: _ - 553 | 《在魔王城说晚安》章节：367 第367话 第三百六十七夜 开幕！全体会议！ - 1 - https://www.biliplus.com/manga/?act=get_image_url&epid=1526627&request_time=1725680973&file=3a92596a1ce830bddabd13bf055d83944ff25441.webp&append= - 下载内容Checksum不正确! 重试中...
	"df4871a82f753ff2bbff900ae1380432" ≠ f2f28695795bea43927ba5e920b1c6fb
11:49:56 | ERROR | Episode: downloadImg - 563 | 《在魔王城说晚安》章节：367 第367话 第三百六十七夜 开幕！全体会议！ - 1 - https://www.biliplus.com/manga/?act=get_image_url&epid=1526627&request_time=1725680973&file=3a92596a1ce830bddabd13bf055d83944ff25441.webp&append= 重复下载图片多次后失败!
```

**Comment by shadlc** [comment]
计划添加是否校验哈希值的开关来解决这个问题
