### ISSUE TITLE
[Bug] 重复测试Cookie是否有效多次后失败!

### ISSUE THREAD

**Issue by chenxiex** [Zeal-L/BiliBili-Manga-Downloader#177]
### 问题描述

Arch Linux系统
也尝试过使用debian bookworm容器运行，结果一样。
在软件中使用二维码登陆或使用网页获取Cookie登陆，可以成功设置Cookie，但是搜索漫画后点击解析，一直卡在“正在解析漫画详情”。关闭软件再打开后弹窗提示“重复测试Cookie是否有效多次后失败!”。搜索漫画后一直卡在“正在解析漫画详情”。

### 预期行为

可以正常解析、下载漫画

### 实际行为

弹窗提示“重复测试Cookie是否有效多次后失败!”。搜索漫画后一直卡在“正在解析漫画详情”

### 哔哩哔哩漫画下载器版本号

v1.5.1

### 系统环境

Linux

### 日志

			------------------- 程序启动，初始化主窗口 -------------------

01:05:28 | INFO | MainGUI: __init__ - 68 | save_method: 文件夹-图片
01:05:28 | WARNING | SettingUI: _ - 180 | 测试Cookie是否有效失败! 状态码：412, 理由: Precondition Failed 重试中...
01:05:29 | WARNING | SettingUI: _ - 180 | 测试Cookie是否有效失败! 状态码：412, 理由: Precondition Failed 重试中...
01:05:30 | WARNING | SettingUI: _ - 180 | 测试Cookie是否有效失败! 状态码：412, 理由: Precondition Failed 重试中...
01:05:31 | WARNING | SettingUI: _ - 180 | 测试Cookie是否有效失败! 状态码：412, 理由: Precondition Failed 重试中...
01:05:35 | WARNING | SettingUI: _ - 180 | 测试Cookie是否有效失败! 状态码：412, 理由: Precondition Failed 重试中...
01:05:35 | ERROR | SettingUI: check_cookie_valid - 191 | 重复测试Cookie是否有效多次后失败!

01:05:35 | ERROR | SettingUI: check_cookie_valid - 192 | 
Traceback (most recent call last):
  File "src/ui/SettingUI.py", line 186, in check_cookie_valid
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src/ui/SettingUI.py", line 183, in _
requests.exceptions.HTTPError

**Comment by chenxiex** [comment]
额外获取Cookie中buvid3一栏的值，然后在Cookie界面手动填入 `SESSDATA;buvid3=buvid3;` 使用B站解析就能解析出漫画详情了。但是启动应用时依然提示Cookie无效，另外下载漫画没有速度，Biliplus解析还是会卡在“正在解析漫画详情”。

**Comment by wf-chen** [comment]
win10也有同样的问题

**Comment by CorvinYu** [comment]
同样问题，系统是win11，望解决❤️❤️

**Comment by LuridG** [comment]
> buvid3

测试可行，只是打开的时候会弹提示说无效，实际可解析。

**Comment by CorvinYu** [comment]
> > buvid3
> 测试可行，只是打开的时候会弹提示说无效，实际可解析。
我试了一下好像不能解析诶，是我什么地方弄错了吗？我把「SESSDATA;buvid3=buvid3;」填在cookie的最前面

**Comment by LuridG** [comment]
> > > buvid3
> > 
> > 
> > 测试可行，只是打开的时候会弹提示说无效，实际可解析。
> 
> 我试了一下好像不能解析诶，是我什么地方弄错了吗？我把「SESSDATA;buvid3=buvid3;」填在cookie的最前面

是<SESSDATA（原本需求的一长串内容）>;（分号）buvid3=<buvid3的那一长串内容>；(分号)，不是直接把它的那个填在的前面。
![image](https://github.com/user-attachments/assets/e05b0a9b-3a6c-4203-b909-918ba21b33aa)

**Comment by chenxiex** [comment]
我看了一下#173 应该已经解决了`buvid3` 的问题，不过还没有合并到main分支。而且加上`buvid3`也仅仅是解决了解析的问题，依然不能下载。

**Comment by LuridG** [comment]
> 我看了一下#173 应该已经解决了`buvid3` 的问题，不过还没有合并到main分支。而且加上`buvid3`也仅仅是解决了解析的问题，依然不能下载。

尝试了develop分支编译使用，bili解析和biliplus解析都没问题了，但是下载下不动。
