### ISSUE TITLE
[Bug] Biliplus下载时校验文件错误

### ISSUE THREAD

**Issue by sprinox** [Zeal-L/BiliBili-Manga-Downloader#61]
### 问题描述

使用Biliplus解析下载，出现错误
版本：[Merge pull request https://github.com/BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader/pull/53 from shadlc/experiment/biliplus](https://github.com/BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader/commit/f34c478c86cfdd82c7781aa5eb1716621a05af83)

可能是`src\BiliPlus.py`校验md5有点问题
```
@ -219,5 +219,5 @@ class BiliPlusEpisode(Episode):
        Returns:
            bool: True: 有效; False: 无效
        """
-       md5 = base64.b64encode(hashlib.md5(content).digest()).decode()
+       md5 = hashlib.md5(content).hexdigest()
        return etag == md5, etag, md5
```

改了一下就能下了

### 预期行为

正常下载

### 实际行为

无法下载

### 截图或录屏

无

### 哔哩哔哩漫画下载器版本号

v1.2.0-alpha

### 系统环境

Windows11

### 日志

```
13:48:13 | INFO | MainGUI: __init__ - 36 | 

			------------------- 程序启动，初始化主窗口 -------------------

13:48:18 | INFO | searchComic: getResults - 59 | 正在搜索漫画:《辉夜》中...
13:48:18 | INFO | searchComic: getResults - 71 | 搜索结果数量:99
13:48:26 | INFO | Comic: getComicCover - 118 | 获取《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》的封面图片中...
13:48:28 | INFO | Comic: getComicCover - 118 | 获取《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》的封面图片中...
13:48:33 | INFO | MangaUI: _ - 701 | 开始下载选中章节, 数量: 1
13:48:34 | WARNING | Episode: _ - 463 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 - 下载内容Checksum不正确! 重试中...
	fbdfc3c66071be060920b593e18f5833 ≠ +9/DxmBxvgYJILWT4Y9YMw==
13:48:36 | WARNING | Episode: _ - 463 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 - 下载内容Checksum不正确! 重试中...
	fbdfc3c66071be060920b593e18f5833 ≠ +9/DxmBxvgYJILWT4Y9YMw==
13:48:37 | WARNING | Episode: _ - 463 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 - 下载内容Checksum不正确! 重试中...
	fbdfc3c66071be060920b593e18f5833 ≠ +9/DxmBxvgYJILWT4Y9YMw==
13:48:39 | WARNING | Episode: _ - 463 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 - 下载内容Checksum不正确! 重试中...
	fbdfc3c66071be060920b593e18f5833 ≠ +9/DxmBxvgYJILWT4Y9YMw==
13:48:43 | WARNING | Episode: _ - 463 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 - 下载内容Checksum不正确! 重试中...
	fbdfc3c66071be060920b593e18f5833 ≠ +9/DxmBxvgYJILWT4Y9YMw==
13:48:50 | WARNING | Episode: _ - 463 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 - 下载内容Checksum不正确! 重试中...
	fbdfc3c66071be060920b593e18f5833 ≠ +9/DxmBxvgYJILWT4Y9YMw==
13:49:04 | WARNING | Episode: _ - 463 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 - 下载内容Checksum不正确! 重试中...
	fbdfc3c66071be060920b593e18f5833 ≠ +9/DxmBxvgYJILWT4Y9YMw==
13:49:04 | ERROR | Episode: downloadImg - 472 | 《辉夜大小姐想让我告白 ~天才们的恋爱头脑战~》章节：第86话 白银父亲想问出来 - 1 - https://manga.hdslb.com/bfs/manga/4344a01e788a42f6c213f656fcbf3de3e846747a.jpg?token=49a2f799288a67ccaf39938c24e8cd72&ts=64d08936&no_cache=1 重复下载图片多次后失败!

13:49:04 | ERROR | Episode: downloadImg - 475 | 
Traceback (most recent call last):
  File "src\Episode.py", line 470, in downloadImg
  File "retrying.py", line 56, in wrapped_f
  File "retrying.py", line 266, in call
  File "retrying.py", line 301, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 251, in call
  File "src\Episode.py", line 466, in _
requests.exceptions.HTTPError

```

**Comment by Zeal-L** [comment]
是的，这个问题是由于BiliPlus最近把API改了，我们还没有更新对应的检测。很抱歉，会在下个版本解决
